version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql    
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_HOST: mysql_db
      MYSQL_USER: movie_api_user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: movie_api
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
